apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: padm2
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - "https://padm2.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: padm2-db
        diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: isbehandlerdialog
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "mpls04.adeo.no"
          ports:
          - port: 1414
        - host: "dokarkiv.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "btsys.prod-fss-pub.nais.io"
      rules:
        - application: padm2pdfgen
        - application: clamav
          namespace: nais-system
        - application: smtss
          namespace: teamsykmelding
        - application: syfohelsenettproxy
          namespace: teamsykmelding
        - application: isbehandlerdialog
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  envFrom:
    - secret: padm2-serviceuser
    - secret: padm2-keystore-pwd
  filesFrom:
    - mountPath: /var/run/keystore
      secret: padm2-keystore
  kafka:
    pool: nav-prod
  env:
    - name: MQ_HOST_NAME
      value: "mpls04.adeo.no"
    - name: MQ_PORT
      value: "1414"
    - name: MQ_GATEWAY_NAME
      value: "MPLS04"
    - name: MQ_CHANNEL_NAME
      value: "P_PADM"
    - name: MQ_KEYSTORE_PATH
      value: "/var/run/keystore/padm2-keystore.jks"
    - name: MQ_INPUT_QUEUE_NAME
      value: "QA.P_PADM.INPUT"
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: "QA.P_PADM.INPUT_BOQ"
    - name: ARENA_OUTBOUND_QUEUENAME
      value: "QA.P414.AO01_SKJEMA_MOTTAK"
    - name: MQ_APPREC_QUEUE_NAME
      value: "QA.P414.IU03_UTSENDING"
    - name: CLAMAV_URL
      value: http://clamav.nais-system
    - name: DOKARKIV_CLIENT_ID
      value: prod-fss.teamdokumenthandtering.dokarkiv
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: PDF_GEN_URL
      value: http://padm2pdfgen/api/v1/genpdf/padm2/padm2
    - name: PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: PDL_ENDPOINT_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: HELSENETT_CLIENT_ID
      value: prod-gcp.teamsykmelding.syfohelsenettproxy
    - name: HELSENETT_ENDPOINT_URL
      value: http://syfohelsenettproxy.teamsykmelding
    - name: LEGE_SUSPENSJON_CLIENT_ID
      value: prod-fss.team-rocket.btsys
    - name: LEGE_SUSPENSJON_ENDPOINT_URL
      value: https://btsys.prod-fss-pub.nais.io
    - name: SMTSS_CLIENT_ID
      value: prod-gcp.teamsykmelding.smtss
    - name: SMTSS_URL
      value: http://smtss.teamsykmelding
    - name: SMGCP_PROXY_CLIENT_ID
      value: prod-fss.teamsykmelding.smgcp-proxy
    - name: SMGCP_PROXY_URL
      value: https://smgcp-proxy.prod-fss-pub.nais.io
    - name: ISBEHANDLERDIALOG_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isbehandlerdialog"
    - name: ISBEHANDLERDIALOG_ENDPOINT_URL
      value: "http://isbehandlerdialog"
