ALTER TABLE DIALOGMELDINGOPPLYSNINGER
ADD COLUMN invalid BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN emottak_subscription TIMESTAMP,
ADD COLUMN journalforing TIMESTAMP,
ADD COLUMN dialogmelding_published TIMESTAMP,
ADD COLUMN arena TIMESTAMP,
ADD COLUMN apprec TIMESTAMP;
