ALTER TABLE DIALOGMELDINGOPPLYSNINGER
ADD COLUMN journalforing            TIMESTAMP DEFAULT '2000-01-01'::TIMESTAMP,
ADD COLUMN journalpostid            VARCHAR(20),
ADD COLUMN dialogmelding_published  TIMESTAMP DEFAULT '2000-01-01'::TIMESTAMP,
ADD COLUMN arena                    TIMESTAMP DEFAULT '2000-01-01'::TIMESTAMP,
ADD COLUMN apprec                   TIMESTAMP DEFAULT '2000-01-01'::TIMESTAMP;
