ALTER TABLE DIALOGMELDINGOPPLYSNINGER ADD COLUMN created_at TIMESTAMP;

UPDATE dialogmeldingopplysninger SET created_at = mottatt_tidspunkt;

ALTER TABLE DIALOGMELDINGOPPLYSNINGER ALTER COLUMN created_at SET NOT NULL;


